report_comment: >
  This MultiQC report aggregates FastQC and kb-python (kallisto|bustools)
  outputs for the nf-scrnaseq pipeline.

report_section_order:
  fastqc:
    order: 1000
  kallisto:
    order: 900
  software_versions:
    order: -1000

export_plots: true
disable_version_detection: false

custom_logo_url: "https://www.nextflow.io/"
custom_logo_title: "nf-scrnaseq"
